/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Format = { 'Doubles' : null } |
  { 'Singles' : null };
export interface LeaderboardEntry {
  'teamName' : string,
  'wins' : bigint,
  'losses' : bigint,
  'matchesPlayed' : bigint,
  'teamId' : bigint,
  'points' : bigint,
}
export interface Match {
  'id' : bigint,
  'matchTime' : string,
  'status' : MatchStatus,
  'set2ScoreA' : bigint,
  'set2ScoreB' : bigint,
  'winnerId' : [] | [bigint],
  'set3ScoreA' : [] | [bigint],
  'set3ScoreB' : [] | [bigint],
  'court' : string,
  'teamAId' : bigint,
  'teamBId' : bigint,
  'bracketSlot' : [] | [bigint],
  'round' : [] | [MatchRound],
  'set1ScoreA' : bigint,
  'set1ScoreB' : bigint,
}
export type MatchRound = { 'LeagueRound1' : null } |
  { 'LeagueRound2' : null } |
  { 'SemiFinal' : null } |
  { 'Final' : null } |
  { 'QuarterFinal' : null };
export type MatchStatus = { 'Scheduled' : null } |
  { 'InProgress' : null } |
  { 'Completed' : null };
export interface Team {
  'id' : bigint,
  'teamName' : string,
  'player1' : string,
  'player2' : [] | [string],
}
export interface TournamentInfo {
  'venue' : string,
  'date' : string,
  'name' : string,
  'format' : Format,
}
export interface _SERVICE {
  'createMatch' : ActorMethod<
    [bigint, bigint, string, string, [] | [MatchRound], [] | [bigint]],
    bigint
  >,
  'createTeam' : ActorMethod<[string, string, [] | [string]], bigint>,
  'deleteMatch' : ActorMethod<[bigint], undefined>,
  'deleteTeam' : ActorMethod<[bigint], undefined>,
  'getAllMatches' : ActorMethod<[], Array<Match>>,
  'getAllTeams' : ActorMethod<[], Array<Team>>,
  'getBracketProgression' : ActorMethod<[], Array<[bigint, [] | [bigint]]>>,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getMatch' : ActorMethod<[bigint], [] | [Match]>,
  'getTeam' : ActorMethod<[bigint], [] | [Team]>,
  'getTournamentInfo' : ActorMethod<[], [] | [TournamentInfo]>,
  'saveMatchScores' : ActorMethod<
    [bigint, bigint, bigint, bigint, bigint, [] | [bigint], [] | [bigint], [] | [bigint]],
    undefined
  >,
  'updateAdminPassword' : ActorMethod<[string, string], boolean>,
  'updateMatch' : ActorMethod<[Match], undefined>,
  'updateTeam' : ActorMethod<
    [bigint, string, string, [] | [string]],
    undefined
  >,
  'updateTournamentInfo' : ActorMethod<[TournamentInfo], undefined>,
  'verifyAdminPassword' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];