/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MatchRound = IDL.Variant({
  'LeagueRound1' : IDL.Null,
  'LeagueRound2' : IDL.Null,
  'SemiFinal' : IDL.Null,
  'Final' : IDL.Null,
  'QuarterFinal' : IDL.Null,
});
export const MatchStatus = IDL.Variant({
  'Scheduled' : IDL.Null,
  'InProgress' : IDL.Null,
  'Completed' : IDL.Null,
});
export const Match = IDL.Record({
  'id' : IDL.Nat,
  'matchTime' : IDL.Text,
  'status' : MatchStatus,
  'set2ScoreA' : IDL.Nat,
  'set2ScoreB' : IDL.Nat,
  'winnerId' : IDL.Opt(IDL.Nat),
  'set3ScoreA' : IDL.Opt(IDL.Nat),
  'set3ScoreB' : IDL.Opt(IDL.Nat),
  'court' : IDL.Text,
  'teamAId' : IDL.Nat,
  'teamBId' : IDL.Nat,
  'bracketSlot' : IDL.Opt(IDL.Nat),
  'round' : IDL.Opt(MatchRound),
  'set1ScoreA' : IDL.Nat,
  'set1ScoreB' : IDL.Nat,
});
export const Team = IDL.Record({
  'id' : IDL.Nat,
  'teamName' : IDL.Text,
  'player1' : IDL.Text,
  'player2' : IDL.Opt(IDL.Text),
});
export const LeaderboardEntry = IDL.Record({
  'teamName' : IDL.Text,
  'wins' : IDL.Nat,
  'losses' : IDL.Nat,
  'matchesPlayed' : IDL.Nat,
  'teamId' : IDL.Nat,
  'points' : IDL.Nat,
});
export const Format = IDL.Variant({
  'Doubles' : IDL.Null,
  'Singles' : IDL.Null,
});
export const TournamentInfo = IDL.Record({
  'venue' : IDL.Text,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'format' : Format,
});

export const idlService = IDL.Service({
  'createMatch' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Opt(MatchRound),
        IDL.Opt(IDL.Nat),
      ],
      [IDL.Nat],
      [],
    ),
  'createTeam' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'deleteMatch' : IDL.Func([IDL.Nat], [], []),
  'deleteTeam' : IDL.Func([IDL.Nat], [], []),
  'getAllMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
  'getAllTeams' : IDL.Func([], [IDL.Vec(Team)], ['query']),
  'getBracketProgression' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Opt(IDL.Nat)))],
      ['query'],
    ),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getMatch' : IDL.Func([IDL.Nat], [IDL.Opt(Match)], ['query']),
  'getTeam' : IDL.Func([IDL.Nat], [IDL.Opt(Team)], ['query']),
  'getTournamentInfo' : IDL.Func([], [IDL.Opt(TournamentInfo)], ['query']),
  'saveMatchScores' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
      ],
      [],
      [],
    ),
  'updateAdminPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'updateMatch' : IDL.Func([Match], [], []),
  'updateTeam' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updateTournamentInfo' : IDL.Func([TournamentInfo], [], []),
  'verifyAdminPassword' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MatchRound = IDL.Variant({
    'LeagueRound1' : IDL.Null,
    'LeagueRound2' : IDL.Null,
    'SemiFinal' : IDL.Null,
    'Final' : IDL.Null,
    'QuarterFinal' : IDL.Null,
  });
  const MatchStatus = IDL.Variant({
    'Scheduled' : IDL.Null,
    'InProgress' : IDL.Null,
    'Completed' : IDL.Null,
  });
  const Match = IDL.Record({
    'id' : IDL.Nat,
    'matchTime' : IDL.Text,
    'status' : MatchStatus,
    'set2ScoreA' : IDL.Nat,
    'set2ScoreB' : IDL.Nat,
    'winnerId' : IDL.Opt(IDL.Nat),
    'set3ScoreA' : IDL.Opt(IDL.Nat),
    'set3ScoreB' : IDL.Opt(IDL.Nat),
    'court' : IDL.Text,
    'teamAId' : IDL.Nat,
    'teamBId' : IDL.Nat,
    'bracketSlot' : IDL.Opt(IDL.Nat),
    'round' : IDL.Opt(MatchRound),
    'set1ScoreA' : IDL.Nat,
    'set1ScoreB' : IDL.Nat,
  });
  const Team = IDL.Record({
    'id' : IDL.Nat,
    'teamName' : IDL.Text,
    'player1' : IDL.Text,
    'player2' : IDL.Opt(IDL.Text),
  });
  const LeaderboardEntry = IDL.Record({
    'teamName' : IDL.Text,
    'wins' : IDL.Nat,
    'losses' : IDL.Nat,
    'matchesPlayed' : IDL.Nat,
    'teamId' : IDL.Nat,
    'points' : IDL.Nat,
  });
  const Format = IDL.Variant({ 'Doubles' : IDL.Null, 'Singles' : IDL.Null });
  const TournamentInfo = IDL.Record({
    'venue' : IDL.Text,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'format' : Format,
  });
  
  return IDL.Service({
    'createMatch' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Opt(MatchRound),
          IDL.Opt(IDL.Nat),
        ],
        [IDL.Nat],
        [],
      ),
    'createTeam' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'deleteMatch' : IDL.Func([IDL.Nat], [], []),
    'deleteTeam' : IDL.Func([IDL.Nat], [], []),
    'getAllMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
    'getAllTeams' : IDL.Func([], [IDL.Vec(Team)], ['query']),
    'getBracketProgression' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Opt(IDL.Nat)))],
        ['query'],
      ),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getMatch' : IDL.Func([IDL.Nat], [IDL.Opt(Match)], ['query']),
    'getTeam' : IDL.Func([IDL.Nat], [IDL.Opt(Team)], ['query']),
    'getTournamentInfo' : IDL.Func([], [IDL.Opt(TournamentInfo)], ['query']),
    'saveMatchScores' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
        ],
        [],
        [],
      ),
    'updateAdminPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'updateMatch' : IDL.Func([Match], [], []),
    'updateTeam' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateTournamentInfo' : IDL.Func([TournamentInfo], [], []),
    'verifyAdminPassword' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };