/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LeaderboardEntry {
    teamName: string;
    wins: bigint;
    losses: bigint;
    matchesPlayed: bigint;
    teamId: bigint;
    points: bigint;
}
export interface TournamentInfo {
    venue: string;
    date: string;
    name: string;
    format: Format;
}
export interface Match {
    id: bigint;
    matchTime: string;
    status: MatchStatus;
    set2ScoreA: bigint;
    set2ScoreB: bigint;
    winnerId?: bigint;
    set3ScoreA?: bigint;
    set3ScoreB?: bigint;
    court: string;
    teamAId: bigint;
    teamBId: bigint;
    bracketSlot?: bigint;
    round?: MatchRound;
    set1ScoreA: bigint;
    set1ScoreB: bigint;
}
export interface Team {
    id: bigint;
    teamName: string;
    player1: string;
    player2?: string;
}
export enum Format {
    Doubles = "Doubles",
    Singles = "Singles"
}
export enum MatchRound {
    LeagueRound1 = "LeagueRound1",
    LeagueRound2 = "LeagueRound2",
    SemiFinal = "SemiFinal",
    Final = "Final",
    QuarterFinal = "QuarterFinal"
}
export enum MatchStatus {
    Scheduled = "Scheduled",
    InProgress = "InProgress",
    Completed = "Completed"
}
export interface backendInterface {
    createMatch(teamAId: bigint, teamBId: bigint, matchTime: string, court: string, round: MatchRound | null, bracketSlot: bigint | null): Promise<bigint>;
    createTeam(teamName: string, player1: string, player2: string | null): Promise<bigint>;
    deleteMatch(id: bigint): Promise<void>;
    deleteTeam(id: bigint): Promise<void>;
    getAllMatches(): Promise<Array<Match>>;
    getAllTeams(): Promise<Array<Team>>;
    getBracketProgression(): Promise<Array<[bigint, bigint | null]>>;
    getLeaderboard(): Promise<Array<LeaderboardEntry>>;
    getMatch(id: bigint): Promise<Match | null>;
    getTeam(id: bigint): Promise<Team | null>;
    getTournamentInfo(): Promise<TournamentInfo | null>;
    saveMatchScores(matchId: bigint, set1ScoreA: bigint, set1ScoreB: bigint, set2ScoreA: bigint, set2ScoreB: bigint, set3ScoreA: bigint | null, set3ScoreB: bigint | null, manualWinnerId: bigint | null): Promise<void>;
    updateAdminPassword(oldPassword: string, newPassword: string): Promise<boolean>;
    updateMatch(match: Match): Promise<void>;
    updateTeam(id: bigint, teamName: string, player1: string, player2: string | null): Promise<void>;
    updateTournamentInfo(info: TournamentInfo): Promise<void>;
    verifyAdminPassword(password: string): Promise<boolean>;
}
import type { Format as _Format, Match as _Match, MatchRound as _MatchRound, MatchStatus as _MatchStatus, Team as _Team, TournamentInfo as _TournamentInfo } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createMatch(arg0: bigint, arg1: bigint, arg2: string, arg3: string, arg4: MatchRound | null, arg5: bigint | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createMatch(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMatch(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async createTeam(arg0: string, arg1: string, arg2: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTeam(arg0, arg1, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTeam(arg0, arg1, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async deleteMatch(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMatch(arg0);
            return result;
        }
    }
    async deleteTeam(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTeam(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTeam(arg0);
            return result;
        }
    }
    async getAllMatches(): Promise<Array<Match>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMatches();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMatches();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTeams(): Promise<Array<Team>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTeams();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTeams();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBracketProgression(): Promise<Array<[bigint, bigint | null]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBracketProgression();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBracketProgression();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaderboard(): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard();
            return result;
        }
    }
    async getMatch(arg0: bigint): Promise<Match | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatch(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatch(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeam(arg0: bigint): Promise<Team | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeam(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeam(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTournamentInfo(): Promise<TournamentInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTournamentInfo();
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTournamentInfo();
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveMatchScores(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint | null, arg6: bigint | null, arg7: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveMatchScores(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveMatchScores(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async updateAdminPassword(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAdminPassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAdminPassword(arg0, arg1);
            return result;
        }
    }
    async updateMatch(arg0: Match): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMatch(to_candid_Match_n28(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMatch(to_candid_Match_n28(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateTeam(arg0: bigint, arg1: string, arg2: string, arg3: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTeam(arg0, arg1, arg2, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTeam(arg0, arg1, arg2, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateTournamentInfo(arg0: TournamentInfo): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTournamentInfo(to_candid_TournamentInfo_n32(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTournamentInfo(to_candid_TournamentInfo_n32(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async verifyAdminPassword(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyAdminPassword(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyAdminPassword(arg0);
            return result;
        }
    }
}
function from_candid_Format_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Format): Format {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_MatchRound_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchRound): MatchRound {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_MatchStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchStatus): MatchStatus {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Match_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Match): Match {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Team_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Team): Team {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_TournamentInfo_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TournamentInfo): TournamentInfo {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MatchRound]): MatchRound | null {
    return value.length === 0 ? null : from_candid_MatchRound_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Match]): Match | null {
    return value.length === 0 ? null : from_candid_Match_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Team]): Team | null {
    return value.length === 0 ? null : from_candid_Team_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TournamentInfo]): TournamentInfo | null {
    return value.length === 0 ? null : from_candid_TournamentInfo_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    teamName: string;
    player1: string;
    player2: [] | [string];
}): {
    id: bigint;
    teamName: string;
    player1: string;
    player2?: string;
} {
    return {
        id: value.id,
        teamName: value.teamName,
        player1: value.player1,
        player2: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.player2))
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    venue: string;
    date: string;
    name: string;
    format: _Format;
}): {
    venue: string;
    date: string;
    name: string;
    format: Format;
} {
    return {
        venue: value.venue,
        date: value.date,
        name: value.name,
        format: from_candid_Format_n26(_uploadFile, _downloadFile, value.format)
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    matchTime: string;
    status: _MatchStatus;
    set2ScoreA: bigint;
    set2ScoreB: bigint;
    winnerId: [] | [bigint];
    set3ScoreA: [] | [bigint];
    set3ScoreB: [] | [bigint];
    court: string;
    teamAId: bigint;
    teamBId: bigint;
    bracketSlot: [] | [bigint];
    round: [] | [_MatchRound];
    set1ScoreA: bigint;
    set1ScoreB: bigint;
}): {
    id: bigint;
    matchTime: string;
    status: MatchStatus;
    set2ScoreA: bigint;
    set2ScoreB: bigint;
    winnerId?: bigint;
    set3ScoreA?: bigint;
    set3ScoreB?: bigint;
    court: string;
    teamAId: bigint;
    teamBId: bigint;
    bracketSlot?: bigint;
    round?: MatchRound;
    set1ScoreA: bigint;
    set1ScoreB: bigint;
} {
    return {
        id: value.id,
        matchTime: value.matchTime,
        status: from_candid_MatchStatus_n9(_uploadFile, _downloadFile, value.status),
        set2ScoreA: value.set2ScoreA,
        set2ScoreB: value.set2ScoreB,
        winnerId: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.winnerId)),
        set3ScoreA: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.set3ScoreA)),
        set3ScoreB: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.set3ScoreB)),
        court: value.court,
        teamAId: value.teamAId,
        teamBId: value.teamBId,
        bracketSlot: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.bracketSlot)),
        round: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.round)),
        set1ScoreA: value.set1ScoreA,
        set1ScoreB: value.set1ScoreB
    };
}
function from_candid_tuple_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, [] | [bigint]]): [bigint, bigint | null] {
    return [
        value[0],
        from_candid_opt_n11(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Scheduled: null;
} | {
    InProgress: null;
} | {
    Completed: null;
}): MatchStatus {
    return "Scheduled" in value ? MatchStatus.Scheduled : "InProgress" in value ? MatchStatus.InProgress : "Completed" in value ? MatchStatus.Completed : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    SemiFinal: null;
} | {
    Final: null;
} | {
    QuarterFinal: null;
}): MatchRound {
    return "LeagueRound1" in value ? MatchRound.LeagueRound1 : "LeagueRound2" in value ? MatchRound.LeagueRound2 : "SemiFinal" in value ? MatchRound.SemiFinal : "Final" in value ? MatchRound.Final : "QuarterFinal" in value ? MatchRound.QuarterFinal : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Doubles: null;
} | {
    Singles: null;
}): Format {
    return "Doubles" in value ? Format.Doubles : "Singles" in value ? Format.Singles : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Team>): Array<Team> {
    return value.map((x)=>from_candid_Team_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, [] | [bigint]]>): Array<[bigint, bigint | null]> {
    return value.map((x)=>from_candid_tuple_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Match>): Array<Match> {
    return value.map((x)=>from_candid_Match_n7(_uploadFile, _downloadFile, x));
}
function to_candid_Format_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Format): _Format {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function to_candid_MatchRound_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MatchRound): _MatchRound {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_MatchStatus_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MatchStatus): _MatchStatus {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid_Match_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Match): _Match {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_TournamentInfo_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TournamentInfo): _TournamentInfo {
    return to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MatchRound | null): [] | [_MatchRound] {
    return value === null ? candid_none() : candid_some(to_candid_MatchRound_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    matchTime: string;
    status: MatchStatus;
    set2ScoreA: bigint;
    set2ScoreB: bigint;
    winnerId?: bigint;
    set3ScoreA?: bigint;
    set3ScoreB?: bigint;
    court: string;
    teamAId: bigint;
    teamBId: bigint;
    bracketSlot?: bigint;
    round?: MatchRound;
    set1ScoreA: bigint;
    set1ScoreB: bigint;
}): {
    id: bigint;
    matchTime: string;
    status: _MatchStatus;
    set2ScoreA: bigint;
    set2ScoreB: bigint;
    winnerId: [] | [bigint];
    set3ScoreA: [] | [bigint];
    set3ScoreB: [] | [bigint];
    court: string;
    teamAId: bigint;
    teamBId: bigint;
    bracketSlot: [] | [bigint];
    round: [] | [_MatchRound];
    set1ScoreA: bigint;
    set1ScoreB: bigint;
} {
    return {
        id: value.id,
        matchTime: value.matchTime,
        status: to_candid_MatchStatus_n30(_uploadFile, _downloadFile, value.status),
        set2ScoreA: value.set2ScoreA,
        set2ScoreB: value.set2ScoreB,
        winnerId: value.winnerId ? candid_some(value.winnerId) : candid_none(),
        set3ScoreA: value.set3ScoreA ? candid_some(value.set3ScoreA) : candid_none(),
        set3ScoreB: value.set3ScoreB ? candid_some(value.set3ScoreB) : candid_none(),
        court: value.court,
        teamAId: value.teamAId,
        teamBId: value.teamBId,
        bracketSlot: value.bracketSlot ? candid_some(value.bracketSlot) : candid_none(),
        round: value.round ? candid_some(to_candid_MatchRound_n2(_uploadFile, _downloadFile, value.round)) : candid_none(),
        set1ScoreA: value.set1ScoreA,
        set1ScoreB: value.set1ScoreB
    };
}
function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    venue: string;
    date: string;
    name: string;
    format: Format;
}): {
    venue: string;
    date: string;
    name: string;
    format: _Format;
} {
    return {
        venue: value.venue,
        date: value.date,
        name: value.name,
        format: to_candid_Format_n34(_uploadFile, _downloadFile, value.format)
    };
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MatchRound): {
    LeagueRound1: null;
} | {
    LeagueRound2: null;
} | {
    SemiFinal: null;
} | {
    Final: null;
} | {
    QuarterFinal: null;
} {
    return value == MatchRound.LeagueRound1 ? {
        LeagueRound1: null
    } : value == MatchRound.LeagueRound2 ? {
        LeagueRound2: null
    } : value == MatchRound.SemiFinal ? {
        SemiFinal: null
    } : value == MatchRound.Final ? {
        Final: null
    } : value == MatchRound.QuarterFinal ? {
        QuarterFinal: null
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MatchStatus): {
    Scheduled: null;
} | {
    InProgress: null;
} | {
    Completed: null;
} {
    return value == MatchStatus.Scheduled ? {
        Scheduled: null
    } : value == MatchStatus.InProgress ? {
        InProgress: null
    } : value == MatchStatus.Completed ? {
        Completed: null
    } : value;
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Format): {
    Doubles: null;
} | {
    Singles: null;
} {
    return value == Format.Doubles ? {
        Doubles: null
    } : value == Format.Singles ? {
        Singles: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
